<a href="https://colab.research.google.com/github/rajni0829/Python/blob/main/Learning_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
## Default name 
x = tf.constant(10,tf.int32)
print(x)


tf.Tensor(10, shape=(), dtype=int32)


In [3]:
# naming
y = tf.constant(10,tf.int32,name="my_conso")
print(y)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
# decimal data
q1 = tf.constant(123.456,tf.float32)
print(q1)

tf.Tensor(123.456, shape=(), dtype=float32)


In [5]:
# string 
q1_str = tf.constant("Heyy!",tf.string)
print(q1_str)

q2_boolean = tf.constant([True, True, False], tf.bool)
print(q2_boolean) 

tf.Tensor(b'Heyy!', shape=(), dtype=string)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [6]:
# 1D Tensor
t1 = tf.constant([1,2,3],tf.int32)
t2 = tf.constant([[1],[2],[3]],tf.int32)
t3 = tf.constant([[[1,2],[3,4],[5,6]]],tf.int32)

print(t1)
print(t2)
print(t3)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int32)


In [7]:
#shape
sh = tf.constant([[11,12],[13,14],[21,76]])
sh


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [21, 76]], dtype=int32)>

In [8]:
# add
t_a = tf.constant([1,2,3],dtype=tf.int32)
t_b = tf.constant([4,5,6],dtype=tf.int32)

sum = tf.add(t_a,t_b)
print(sum)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [9]:
# sub
t_a = tf.constant([[14,20,30]],dtype=tf.int32)
t_b = tf.constant([[4,5,6]],dtype=tf.int32)

sub = tf.subtract(t_a,t_b)
print(sub)

tf.Tensor([[10 15 24]], shape=(1, 3), dtype=int32)


In [10]:
#divide
div = tf.divide(t_a,t_b)
div

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[3.5, 4. , 5. ]])>

In [11]:
x = tf.constant([9.0],dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor([3.], shape=(1,), dtype=float32)


In [12]:
# creating var
var = tf.Variable("var",[1,2])
print(var.shape)
print(var.name)

()
Variable:0


In [13]:
x = tf.constant([2], dtype=tf.int32)
f = tf.constant([5], dtype=tf.int32)
print(tf.pow(x,f))


tf.Tensor([32], shape=(1,), dtype=int32)


In [14]:
#Exponent
y = tf.constant([2.0], dtype=tf.float32)
print(tf.exp(y))


tf.Tensor([7.389056], shape=(1,), dtype=float32)


In [15]:
# placeholder
import warnings
warnings.filterwarnings("ignore")

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

pl = tf.placeholder(tf.int32,shape=None,name="She")
print(pl)

Instructions for updating:
non-resource variables are not supported in the long term
Tensor("She:0", dtype=int32)


In [16]:
# Creating Two Sensors
x = tf.constant([1,2],tf.int32)
y = tf.constant([3,4],tf.int32)

In [17]:
# creating operator
mul = tf.multiply(x,y)
mul

<tf.Tensor 'Mul:0' shape=(2,) dtype=int32>

In [18]:
# Opening a session
session = tf.Session()
res = session.run(mul)
print(res)
session.close()

[3 8]
