<a href="https://colab.research.google.com/github/rajni0829/Python/blob/main/SolvingEquations_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf

In [23]:
# creating tensors
w = tf.constant([[1,2,3],[5,6,7],[9,10,11],[4,8,12]],tf.int32)
w

<tf.Tensor 'Const_2:0' shape=(4, 3) dtype=int32>

In [24]:
x = tf.constant([[1],[5],[9],[4]],tf.int32)
x

<tf.Tensor 'Const_3:0' shape=(4, 1) dtype=int32>

In [25]:
mul_a = tf.multiply(w,x)
mul_a

<tf.Tensor 'Mul_1:0' shape=(4, 3) dtype=int32>

In [26]:
mul_b = tf.multiply(x,mul_a)
mul_b

<tf.Tensor 'Mul_2:0' shape=(4, 3) dtype=int32>

In [27]:
sum = tf.add(mul_a,mul_b)
sum

<tf.Tensor 'Add_5:0' shape=(4, 3) dtype=int32>

In [28]:
ans = tf.add(sum,x)
ans

<tf.Tensor 'Add_6:0' shape=(4, 3) dtype=int32>

In [29]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# opening a session
sess = tf.Session()
res = sess.run(ans)
print(res)
sess.close()

[[  3   5   7]
 [155 185 215]
 [819 909 999]
 [ 84 164 244]]


In [30]:
# another method to create a session 
with tf.Session() as sess:
  result_2 = ans.eval()
print(result_2)


[[  3   5   7]
 [155 185 215]
 [819 909 999]
 [ 84 164 244]]


In [18]:
import numpy as np
data_placeholder =tf.placeholder(tf.int32,name="placeholder")
power_a = tf.pow(data_placeholder, 3)


In [19]:
with tf.Session() as sess:
  data = np.random.rand(1, 11)                                  # Create any random array in data
  print(sess.run(power_a, feed_dict={data_placeholder:data}))   # Provide the placeholder into data.
sess.close()

[[0 0 0 0 0 0 0 0 0 0 0]]


In [35]:
# Now taking random values and calc the ans
x1 = tf.get_variable("x",dtype=tf.int32, initializer=tf.constant([5]))
y = tf.get_variable("y",dtype=tf.int32,initializer=tf.constant([10]))
# a = 
# b = 
print(x1)
print(y)
x = tf.compat.v1.get_variable("x", dtype=tf.int32,initializer=tf.constant([5]))
z = tf.compat.v1.get_variable("z", dtype=tf.int32, initializer=tf.constant([6]))
c = tf.constant([5], name ="constant")
square = tf.constant([2], name ="square")
f = tf.multiply(x, z) + tf.pow(x, square) + z + c
print(f)

<tf.Variable 'x:0' shape=(1,) dtype=int32>
<tf.Variable 'y:0' shape=(1,) dtype=int32>
Tensor("add_21:0", shape=(1,), dtype=int32)
