<a href="https://colab.research.google.com/github/rajni0829/Python/blob/main/Tensorflow_Graphs_Pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AIM: 1. Program of Creating a Graph in Tensorflow With Multiple Math Operations  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  2. Program of Tensorflow Session  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Program of Tensorflow Pipeline  



In [8]:
import tensorflow as tf

In [2]:
print(tf.compat.v1.get_default_graph())

In [3]:
x = tf.Graph()
x

In [29]:

t_a = tf.constant([1,2,3],dtype=tf.int32)
t_b = tf.constant([4,5,6],dtype=tf.int32)


In [30]:
ad = tf.add(t_a,t_b)
sub = tf.subtract(t_a,t_b)
mul = tf.multiply(t_a,t_b)
div = tf.divide(t_a,t_b)
power = tf.pow(t_a,t_b)


In [31]:
# Session
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

sess = tf.Session()
ad_graph = sess.run(ad)
sub_graph = sess.run(sub)
mul_graph = sess.run(mul)
div_graph = sess.run(div)
power_graph = sess.run(power)


In [32]:
 ad_graph 

array([5, 7, 9], dtype=int32)

In [33]:
sub_graph

array([-3, -3, -3], dtype=int32)

In [34]:
mul_graph

array([ 4, 10, 18], dtype=int32)

In [35]:
div_graph

array([0.25, 0.4 , 0.5 ])

In [36]:
power_graph

array([  1,  32, 729], dtype=int32)

In [37]:
sess.close()

In [38]:
with tf.Session() as sess:
  print(sess.run(div))


[0.25 0.4  0.5 ]


---> PIPELINES


In [11]:
# TensorFlow pipeline
import random as rn
import numpy as np
import tensorflow as tf


In [10]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [13]:
# creating data
x = np.random.sample((1,2))
print(x)

[[0.10526549 0.36053539]]


In [15]:
# creating placeholder
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

pl = tf.placeholder(tf.float32,shape=[1,2],name="X")
pl

Instructions for updating:
non-resource variables are not supported in the long term


<tf.Tensor 'X:0' shape=(1, 2) dtype=float32>

In [16]:
# defining dataset
tf.data.Dataset.from_tensor_slices
dataset = tf.data.Dataset.from_tensor_slices(x)

In [17]:
# creating pipeline
# loading pp where data is flowing - 
iterator = dataset.make_initializable_iterator()   # creating iterator
print(iterator)


Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.


In [18]:
# Use value_type to see the type of value represented by the element spec
dataset.element_spec.value_type

tensorflow.python.framework.ops.Tensor

In [19]:
# calling iterator to feed next batch of data
get_next = iterator.get_next()
get_next

<tf.Tensor 'IteratorGetNext:0' shape=(2,) dtype=float64>

In [21]:
# executing operation

# initialize session & run operation iterator
with tf.Session() as sess:
  # feeding placeholder into data
  sess.run(iterator.initializer,feed_dict={pl:x})
  print(sess.run(get_next))

[0.10526549 0.36053539]


In [22]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

images, labels = train
images = images/255.0
labels = labels.astype(np.int32)

4431872/4422102 [==============================] - 0s 0us/step


In [23]:
fmnist_train_ds = tf.data.Dataset.from_tensor_slices((images, labels))
fmnist_train_ds = fmnist_train_ds.shuffle(5000).batch(32)

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
              metrics=['accuracy'])

In [25]:
model.fit(fmnist_train_ds, epochs=2)

Train on 1875 steps
Epoch 1/2
1875/1875 [==============================] - 3s 1ms/step - batch: 937.0000 - size: 1.0000 - loss: 0.5984 - acc: 0.7970
Epoch 2/2
1875/1875 [==============================] - 2s 1ms/step - batch: 937.0000 - size: 1.0000 - loss: 0.4612 - acc: 0.8415


In [26]:
model.fit(fmnist_train_ds.repeat(), epochs=2, steps_per_epoch=20)

Train on 20 steps
Epoch 1/2
20/20 [==============================] - 0s 2ms/step - batch: 9.5000 - size: 1.0000 - loss: 0.4237 - acc: 0.8609
Epoch 2/2
20/20 [==============================] - 0s 1ms/step - batch: 9.5000 - size: 1.0000 - loss: 0.4756 - acc: 0.8344
